### PR TITLE
bash: Add bash completion script

### LINKED ISSUE #31: ship a bash/zsh completion script
My  hands hurt from typing.

### PR DESCRIPTION
**Pull request by thalman**
This script provides bash completion for authselect
command. Enable completion by putting this file
into /etc/bash_completion.d directory.

Resolves #31

### CODE REVIEW

**Comment by pbrezina** [comment]
Works great! Thank you.

One think I do not understand - how did you manage to provide completion also for features (`with-*`)? I do not see it anywhere in the script.

**Comment by thalman** [comment]
> One think I do not understand - how did you manage to provide completion also for features (`with-*`)? I do not see it anywhere in the script.

It is on line 88
```bash
if [[ "$profile" != "" ]] ; then
    authselect show "$profile" 2>/dev/null | grep -E "^w.+::$" | cut -d":" -f1`
fi
```

**Comment by pbrezina** [comment]
Thank you. I opened https://github.com/pbrezina/authselect/pull/154 which adds list-features command so the bash completion does not have to depends on profile's documentation. Please, use this command  instead.

Also please move this script in `src/cli/`. I will later make sure it is properly installed and packaged.

**Comment by thalman** [comment]
@pbrezina updated to use list-features, moved to src/cli/

**Comment by thalman** [comment]
Ups, wrong button clicked

**Comment by pbrezina** [comment]
Users often use `sudo` to promote themselves to root so I think it would be good to provide complete completion even for non-root users. All informations are available for non-root users anyway because the configuration needs to be readable by all, only changes are prohibited.

**Comment by pbrezina** [comment]
Also the following commands do not complete all options options:
* `apply-changes`: `-b`, `--backup=NAME`
* `current`: `-r`
* `create-profile`: all of them
* `backup-list`: `-r`, `--raw`

**Comment by thalman** [comment]
> Also the following commands do not complete all options options:
> 
>     * `apply-changes`: `-b`, `--backup=NAME`
> 
>     * `current`: `-r`
> 
>     * `create-profile`: all of them
> 
>     * `backup-list`: `-r`, `--raw`

Thank you for review. I added missing long options. 

It is a habit that completion provides only long options variants. Probably because they are descriptive and expanding the short ones is not really helpful.

Therefore I suggest not to add short versions (-r, -b)

**Comment by pbrezina** [comment]
I found two more missing options, please merge this diff if it is ok:
```
diff --git a/src/cli/authselect-completion.sh b/src/cli/authselect-completion.sh
index f1fe7a8..beabb10 100755
--- a/src/cli/authselect-completion.sh
+++ b/src/cli/authselect-completion.sh
@@ -102,9 +102,12 @@ _authselect_completions()
                 select)
                     echo "--force --quiet --nobackup --backup"
                     ;;
-                apply-changes)
+                apply-changes|disable-feature)
                     echo "--backup"
                     ;;
+                enable-feature)
+                    echo "--backup --quiet"
+                    ;;
                 current|backup-list)
                     echo "--raw"
                     ;;
```

Also some of the options like `--backup` or `--symlink` requires parameter. What is the habit here? Wouldn't it be better if the completion implied it by adding equal sign at the end like `--backup=`?

**Comment by thalman** [comment]
You were right about = in parametrized options.

I had to change the file into .in template and update Makefile so we can expand location of profiles during compilation time.

Now completions for parametrized options --symlink and --based-on works

**Comment by pbrezina** [comment]
`backup-restore` command will complete backup name multiple times if you press multiple tabs. Can this be avoided?
```
authselect backup-restore 2018-08-23-10-59-03.ikVB8T 2018-08-23-10-59-03.ikVB8T 2018-08-23-10-59-03.ikVB8T 2018-08-23-10-59-03.ikVB8T
```

Also I suggest the following changes:
- keep the file untemplated by putting file names for `--symlink=` option directly to the completion script. I think it is ok and since your implementation does not depend on `--base-on` and `--base-on-deafault` it does not really matter.
- add missing parameters to `test` command. These were missing in manpage as well, I will open PR for it.
- add the script to `EXTRA_DIST` in `src/cli/Makefile.am`

If you agree, I will squash the following diff:
```
---diff
 Makefile.am                                                       |  1 -
 src/cli/Makefile.am                                               | 18 +-----------------
 src/cli/{authselect-completion.sh.in => authselect-completion.sh} | 15 ++++++++++++---
 3 files changed, 13 insertions(+), 21 deletions(-)

diff --git a/Makefile.am b/Makefile.am
index 78bb539..5ceeaca 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -24,7 +24,6 @@ EXTRA_DIST = \
     scripts/release-version.sh \
     scripts/po-linguas.sh \
     scripts/zanata-hooks.sh \
-    src/cli/authselect-completion.sh.in \
     $(NULL)

 # Create authselect directories
diff --git a/src/cli/Makefile.am b/src/cli/Makefile.am
index 418a20e..2773426 100644
--- a/src/cli/Makefile.am
+++ b/src/cli/Makefile.am
@@ -29,22 +29,6 @@ authselect_CFLAGS = \
     -DAUTHSELECT_BACKUP_DIR=\"$(authselect_backup_dir)\" \
     $(NULL)

-expand_vars = $(SED) \
-    -e 's,@AUTHSELECT_PROFILE_DIR[@],$(AUTHSELECT_PROFILE_DIR),'g \
-    $(NULL)
-
-generated_files = \
+EXTRA_DIST = \
     authselect-completion.sh \
     $(NULL)
-
-expand_files:
-       for FILE in $(generated_files) ; do \
-               $(expand_vars) < $(srcdir)/$$FILE.in > $$FILE ; \
-       done
-
-.PHONY: expand_files
-BUILT_SOURCES = expand_files
-
-CLEANFILES = \
-    $(generated_files) \
diff --git a/src/cli/authselect-completion.sh.in b/src/cli/authselect-completion.sh
similarity index 88%
rename from src/cli/authselect-completion.sh.in
rename to src/cli/authselect-completion.sh
index a7f0c87..c12ca6c 100644
--- a/src/cli/authselect-completion.sh.in
+++ b/src/cli/authselect-completion.sh
@@ -113,8 +113,15 @@ _authselect_completions()
                     echo "--raw"
                     ;;
                 create-profile)
-                    echo "--vendor --base-on= --base-on-default --symlink-meta --symlink-nsswitch" \
-                         "--symlink-pam --symlink-dconf --symlink="
+                    echo "--vendor --base-on= --base-on-default" \
+                         "--symlink-meta --symlink-nsswitch --symlink-pam" \
+                         "--symlink-dconf --symlink="
+                    ;;
+                test)
+                    echo "--all --nsswitch --system-auth --password-auth" \
+                         "--smartcard-auth --fingerprint-auth --postlogin" \
+                         "--dconf-db --dconf-lock"
+                    ;;
             esac
         fi
     }
@@ -142,7 +149,9 @@ _authselect_completions()
             authselect list 2>/dev/null | cut -d" " -f2
             ;;
         --symlink)
-            find @AUTHSELECT_PROFILE_DIR@ -type f | sed -r -e sx^.+/xx | sort | uniq
+            echo "dconf-db dconf-locks fingerprint-auth nsswitch.conf" \
+                 "password-auth postlogin smartcard-auth system-auth" \
+                 "README REQUIREMENTS"
             ;;
         esac
     }
```

**Comment by thalman** [comment]
PR updated

**Comment by pbrezina** [comment]
Thank you for your hard work and I'm sorry it has so many iterations, but I keep finding issues. These were probably introduced with your recent changes.

* It does not complete `--` parameters unless there is already a free parameter: `authselect select --`, this seems to be problem only with commands that expect profile or feature name [1]
* `create-profile` completes profile names when it is not relevant, apparently because I used the `test` profile name which is also an authselect command:
```
$ authselect create-profile test
nis      sssd     winbind  
```

Otherwise all options are there and it works splendidly.

[1] I actually found there is a bug in parameters processing: https://github.com/pbrezina/authselect/pull/169

**Comment by thalman** [comment]
>     * It does not complete `--` parameters unless there is already a free parameter: `authselect select --`, this seems to be problem only with commands that expect profile or feature

I was too focused on man page where there is `show profile [opts]`. I did not realize at that moment
that `show [opts] profile` works too :)

> 
> ```
> $ authselect create-profile test
> nis      sssd     winbind  
> ```
This is also fixed with the last change.

**Comment by pbrezina** [comment]
`authselect select --force sssd <tab><tab>` does not show available features. It works if the profile name is the first parameter.

**Comment by thalman** [comment]
Fixed

**Comment by pbrezina** [comment]
Thank you. This is hopefully last one: `authselect enable-feature --backup= <tab><tab>` should print feature list, it works with other options (e.g. `--quiet`).

**Comment by thalman** [comment]
I did some updates to be able expand options in different situations but `--backup=<nothinghere>` 
breaks it anyway.

The cause is how bash parses the command line and passes it to completion script.
We can't detect any difference between `--backup=<space>nis` and `--backup=nis`.
In both cases it expands into array `(--backup, =, nis)`.

**Comment by pbrezina** [comment]
Ok. Thank you for investigation. Ack.

**Comment by pbrezina** [comment]
* `master`
  * b9d77ad6225ce8ab1fa3c0833d968d6da9409f0d - bash: Add bash completion script

**Pull request closed without merging**
