### PR TITLE
Make test build more strict about warnings

### PR DESCRIPTION
**Pull request by thalman**
We want to know about warnings in the code and fix them.
Therefore we set environment variable CFLAGS

CFLAGS="-Wall -Wextra -Werror -Wno-sign-compare -Wno-unused-parameter -ggdb3"

### CODE REVIEW

**Comment by pbrezina** [comment]
Apparently there is [this option](https://blog.travis-ci.com/2013-11-27-fast-finishing-builds) that can be used instead:

```yaml
matrix:
  fast_finish: true
```

The rpm build fails because your `CFLAGS` do not generate debug information. I'm not sure what is the default `CFLAGS` value in the docket machine but it would be better to keep it. If it will not help, then you can add `-ggdb3` to the `CFLAGS` value instead of unsetting it. Something like:

```
env:
  global:
  - AUHTSELECT_CFLAGS="-Wall -Wextra -Werror -Wno-sign-compare -Wno-unused-parameter"

before_install:
    ...
    - docker run -d --rm --name AUTHSELECT-FEDORA -e AUTHSELECT_CFLAGS -v `pwd`:/buildroot fedora /bin/sh -c "echo CFLAGS=\"$CFLAGS $AUTHSELECT_CFLAGS\" >> ~/.bashrc"
```

**Comment by thalman** [comment]
> 
> ```yaml
> matrix:
>   fast_finish: true
> ```
> 
Not really. This options is for "matrix" build (several builds running in parallel with different settings).
I found several discussion on this topic and it seems that solution is to do it as I suggest.

> The rpm build fails because your `CFLAGS` do not generate debug information. I'm not sure what is the default `CFLAGS` value in the docker machine but it would be better to keep it.
There is no default for `CFLAGS`, it is ours setting in `.travis.yml`.

 I will try with -g. Thanks for this hint

**Comment by thalman** [comment]
PR updated, please review

**Comment by pbrezina** [comment]
Thank you for explanation.  Please, just squash `-ggdb3 to the first patch. I will push it after this change.

**Comment by thalman** [comment]
Done.

**Comment by pbrezina** [comment]
Before I push it - is there any reason why you removed `docker stop AUTHSELECT-FEDORA` or is this a mistake?

**Comment by thalman** [comment]
There were two docker commands actually without any real effect. This `docker stop` and also `docker ps` in `before_install` section. Docker service is stopped at the end of build with Travis container itself.

So removing it is intentional.

**Comment by pbrezina** [comment]
Thank you.

**Comment by pbrezina** [comment]
* `master`
  * bd5fc9ef878f50ee3e8349515a7252826656187c - Fail the build on first error
  * 0122a1eaa9ec920642e203b0aeed62299867a180 - Make test build more strict about warnings

**Pull request closed without merging**
