### PR TITLE
use Zanata hooks to manage localization

### PR DESCRIPTION
**Pull request by pbrezina**
This patch set reworks manual page build system so it can be properly translated. Translations pushed and pulled using zanata-cli and pot files are located at `po/*` (messages) and `src/man/po/*` (manual pages).

Resolves:
* https://github.com/pbrezina/authselect/issues/56

## Usage
* Push pot files to Zanata
```bash
cd authselect-source-dir
autoreconf -if
./configure --enable-silent-rules
zanata-push
```
* Pull pot files from Zanata
```bash
cd authselect-source-dir
zanata-pull
```

Pot files are made part of authselect distribution. Translations and compiled manual pages are created during `make`.

## How to test
I have simple test version prepared in Zanata, with few strings translations in Czech language. To test it, run:

```bash
zanata-cli pull --project-version test-do-not-translate -l cs
```
## Questions
1. I have not found a way to specify `--min-doc-percent` parameter in zanata.xml. Does somebody know the answer?

### CODE REVIEW

**Comment by jhrozek** [comment]
You should probably detect if the build system has po4a-translate during configure to avoid messages like:
```
/home/remote/jhrozek/devel/authselect/obj/scripts/manpages-build.sh: line 141: po4a-translate: command not found
Unable to translate manual page: *.po, *.po
```
and if it's not present, don't call the binary.

**Comment by jhrozek** [comment]
About the threshold, I don't know how to set that on the zanata side, but po4a-translate has the option -k/--keep which allows you to specify the threshold.

**Comment by jhrozek** [comment]
Even with the new patches I see two issues, one of them may be just a warning, not sure.

1) If I don't have po4a installed, I get this:
```
/home/remote/jhrozek/devel/authselect/scripts/manpages-build.sh "/usr/local" "/usr/local"
Translating /home/remote/jhrozek/devel/authselect/src/man/*.po to *.po
/home/remote/jhrozek/devel/authselect/scripts/manpages-build.sh: line 141: po4a-translate: command not found
Unable to translate manual page: *.po, *.po
```

2) Even with po4a installed, I see:
```
find: ‘./po’: No such file or directory
/home/remote/jhrozek/devel/authselect/scripts/manpages-build.sh "/usr/local" "/usr/local"
Translating /home/remote/jhrozek/devel/authselect/src/man/*.po to *.po
File /home/remote/jhrozek/devel/authselect/src/man/*.po does not exist.
Unable to translate manual page: *.po, *.po
```

Not sure if the second one can be ignored or not.

**Comment by pbrezina** [comment]
Yeah, sorry. These patches are just rebased on top of current master. I'm working on those fixes right now.

**Comment by pbrezina** [comment]
And I set `--keep 80`. For testing, you can overwrite this to 0.

**Comment by pbrezina** [comment]
Thank you.

Pushed to master:
* 5a09d6dfddf6940966f45695e2f49dcc447b864e
* e4b9df6abe5d8b05d63d22df287dbdcd15115221
* f5803ed7b5a39c838e585e885bc5df823677159d
* 8b9cc080c68e6ee50ab4ec14f7439e65a90a41da
* 9814741f2fd21a629f65b7852961aa29091c46e5
* 3b159e5efe0b3aceb94139fbdf0d722db0c61b2e
* 194f2c6168c71e1eb6e13e1cec5c5da1aacd37c9
* ddac857bfa8ed4d9d4d88fdc631aa378953b16dd

**Pull request closed without merging**
